feature: Первая версия сервис для шеринга
verazhadovskaya/java-shareit pull request #1
Opened 2023-11-21 09:33 UTC by verazhadovskaya

2023-11-21 15:29 UTC, EugeneLenkevich requested changes
Привет, Вера! Спасибо за PR.

Отличная работа! :)
Но, убрать бы логику из контроллеров, так будет правильнее с архитектурной точки зрения, посмотри комментарии ниже, пожалуйста

Вообще, у каждого слоя свои обязанности, и, по классике, обязанности распределяются вот так

> Первый слой абстракции — это слой доступа к данным. В задачи данного слоя входит абстрагирование от базы данных. SQL-запросы к базе данных, в которой и хранятся данные приложения, скрываются за фасадом, который использует бизнес-слой.
> 
> Второй слой абстракции — это слой бизнес-логики. Он содержит объекты предметной области, а также функции для работы с ними. Эти функции и реализуют данную бизнес-логику.
> 
> Третий слой абстракции — это слой взаимодействия с пользователем. Данный слой включает компоненты пользовательского интерфейса.

2023-11-21 15:29 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (text.isEmpty()) {
Если text == null, то мы получим ошибку, тут бы еще проверку

ну или взять готовое решение, типа StringUtils.hasText(text) :)

2023-11-21 15:29 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (itemRequest.getAvailable() == null || itemRequest.getName() == null
По своей сути контроллер только обрабатывает (маршрутизирует сервисам) запросы, а тут же в контроллере выполняется некоторая бизнес-логика, ее лучше перенести в сервис, иначе логика размазывается по нескольким классам :)

2023-11-21 15:31 UTC, EugeneLenkevich requested changes
.

2023-11-21 15:31 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        if (userRequest.getEmail() == null || !userRequest.getEmail().contains("@")) {
Это конечно все можно было бы сделать аннотациями, примерно такими
```
@NotBlank
@Email
```

но раз у нас сделано кодом то лучше в сервис :)

2023-11-26 18:48 UTC, verazhadovskaya commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (text.isEmpty()) {
исправила

2023-11-26 18:56 UTC, verazhadovskaya commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (itemRequest.getAvailable() == null || itemRequest.getName() == null
вынесла условия их контроллеров.
Я думала, что можно тут тоже поставить условия, чтобы проверять как можно раньше (ну то есть мы же сразу можем понять пришел ли в запросе тот или иной параметр)...

2023-11-26 18:59 UTC, verazhadovskaya commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        if (userRequest.getEmail() == null || !userRequest.getEmail().contains("@")) {
возможно, я что-то делаю не так. но я установила @NotBlank, @Email - а ошибка не возникала(

2023-11-27 05:27 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (itemRequest.getAvailable() == null || itemRequest.getName() == null
Эта логика понятна, с одной стороны все верно, но с другой стороны нам надо обеспечить единообразие, наш сервис может вызывать не только контроллер, а например другой сервис и тогда поведение будет отличаться :)

2023-11-27 05:35 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-11-27 05:35 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            text = "-1";
Можно сразу возвращать пустой список :)

return List.of();

2023-11-27 05:35 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        if (userRequest.getEmail() == null || !userRequest.getEmail().contains("@")) {
С ходу не скажу, надо ковырять и разбираться, вроде все зависимости на месте зависимости . Пусть будет пока как есть

2023-12-17 12:00 UTC, merged